name: Daily Market Update
on:
  schedule:
    - cron: '30 10 * * 1-5' # Runs at 4:00 PM IST, Monday-Friday
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install libraries
        run: pip install -r requirements.txt
      - name: Run analysis
        run: python script.py
      - name: Deploy to Website
        run: |
          git config --global user.name "GitHub Action"
          git add index.html
          git commit -m "Updated Market Data"
          git push
